pipeline:
  name: PipelineRRR
  identifier: PipelineRRR
  projectIdentifier: TestProject
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: S12
        identifier: S12
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  name: s123
                  identifier: s123
                  template:
                    templateRef: InlineTemplate
                    versionLabel: v1
                    templateInputs:
                      type: ShellScript
                      spec:
                        executionTarget: <+input>
                        delegateSelectors: <+input>
                        source:
                          type: Inline
                          spec:
                            script: <+input>
                        includeInfraSelectors: <+input>
                        outputAlias:
                          key: <+input>
                      timeout: <+input>
        tags: {}
