pipeline:
  name: PpelineRT0001
  identifier: PpelineRT0001
  tags: {}
  template:
    templateRef: PipelineRT001
    versionLabel: v1
    templateInputs:
      stages:
        - stage:
            identifier: S23
            template:
              templateInputs:
                type: Custom
                spec:
                  execution:
                    steps:
                      - step:
                          identifier: S123
                          template:
                            templateInputs:
                              type: ShellScriptProvision
                              timeout: <+input>
                              spec:
                                source:
                                  type: Inline
                                  spec:
                                    script: <+input>
  projectIdentifier: TestProject
  orgIdentifier: default
