pipeline:
  name: PipelineTempTest
  identifier: PipelineTempTest
  tags: {}
  template:
    templateRef: TestPipelineRemote
    versionLabel: v1
  projectIdentifier: ShivamTemplate
  orgIdentifier: default
