pipeline:
  name: RemotePIpelineTestt20
  identifier: RemotePIpelineTestt20
  projectIdentifier: ShivamProject
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: S123
        identifier: S123
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo "Hello"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
              - stepGroup:
                  name: S12
                  identifier: S12
                  template:
                    templateRef: account.StepGroupTempV121
                    versionLabel: v1
                    templateInputs:
                      steps:
                        - step:
                            identifier: S123
                            template:
                              templateInputs:
                                type: ShellScript
                                spec:
                                  source:
                                    type: Inline
                                    spec:
                                      script: <+input>
        tags: {}
