pipeline:
  name: RemotePIpelineTestt120
  identifier: RemotePIpelineTestt120
  projectIdentifier: ShivamProject
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: S123
        identifier: S123
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo "Hello"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
