pipeline:
  name: Sttgasds
  identifier: Sttgasds
  projectIdentifier: ShivamProject
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: S123
        identifier: S123
        tags: {}
        template:
          templateRef: StageTempRemo
          versionLabel: v1
          gitBranch: main
          templateInputs:
            type: Custom
            variables:
              - name: v1
                type: String
                value: <+input>
