pipeline:
  name: Pipelinremote23444
  identifier: Pipelinremote23444
  projectIdentifier: TestProject
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: testV1
        identifier: testV1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo "Hello"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
