name: Wait for External CI Status

on:
  workflow_dispatch:

jobs:
  wait-for-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Poll for External CI Status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          SHA: ${{ github.sha }}
        run: |
          for i in {1..30}; do
            STATUS=$(curl -s -H "Authorization: Bearer ${GITHUB_TOKEN}" \
              https://api.github.com/repos/${OWNER}/${REPO}/commits/${SHA}/status | jq -r '.state')

            echo "Current Status: $STATUS"

            if [ "$STATUS" == "success" ]; then
              echo "External CI succeeded!"
              exit 0
            elif [ "$STATUS" == "failure" ]; then
              echo "External CI failed!"
              exit 1
            fi

            echo "Waiting for CI status... attempt $i"
            sleep 30
          done

          echo "Timeout waiting for CI status"
          exit 1
