name: Set Commit Status

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  set-status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set GitHub Commit Status
        uses: actions/github-script@v6
        with:
          script: |
            const sha = process.env.GITHUB_SHA;
            const context = 'ci/build'; // Customize this as per your requirement
            const state = 'success';    // Can be 'success', 'failure', 'error', or 'pending'
            const description = 'CI build passed!'; // Short description
            const target_url = 'https://ci.example.com/build/1234'; // Optional

            const response = await github.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: sha,
              state: state,
              target_url: target_url,
              description: description,
              context: context,
            });

            console.log(response);
